### ISSUE TITLE
Donation message keeps appearing 

### ISSUE THREAD

**Issue by tdgrossi** [coccoinomane/crabada.py#113]
When closing looting with bot, the donation message keeps appearing along with an error message:

```
src.common.logger - WARNING -
🦀  🦀  🦀

Building Crabada.py requires time and passion.
Please consider expressing your gratitude
by donating a small % of your rewards :-)

To donate, write DONATE_PERCENTAGE=5%
in your .env file; this message will
disappear regardless of the amount that
you donate 🙂

Thank you!

🙏  ❤️  🙏

--- Logging error ---
Traceback (most recent call last):
  File "C:\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f980' in position 58: character maps to <undefined>
Call stack:
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\GitHub\crabada.py\bin\looting\runLoot.py", line 34, in <module>
    run(User(userAddress), sleep_timer, sleep_timer_minor)
  File "C:\GitHub\crabada.py\src\bot\looting\runLoot.py", line 26, in run
    nClosed = closeLoots(user)
  File "C:\GitHub\crabada.py\src\bot\looting\closeLoots.py", line 55, in closeLoots
    maybeDonate(txReceipt)
  File "C:\GitHub\crabada.py\src\helpers\donate.py", line 65, in maybeDonate
    logger.warning(getDonateMessage())
Message: '\n🦀  🦀  🦀\n\nBuilding Crabada.py requires time and passion.\nPlease consider expressing your gratitude\nby donating a small % of your rewards :-)\n\nTo donate, write DONATE_PERCENTAGE=5%\nin your .env file; this message will\ndisappear regardless of the amount that\nyou donate 🙂\n\nThank you!\n\n🙏  ❤️  🙏\n'
Arguments: ()
src.common.logger - DEBUG - Closed loots count is 1, waiting for 20
````

**Comment by yigitest** [comment]
Hi,
I guess that shouldn't prevent the bot from working. You can use this [new branch](https://github.com/coccoinomane/crabada.py/tree/FIX/logging-encoding-error) for now or wait for master branch to update.

pinging @coccoinomane  to review the pull request.

**Comment by coccoinomane** [comment]
Thank you @yigitest for the speed-of-light fix 💪 

I have merged the fix to master: @tdgrossi could you please check whether the error message disappears?

Thanks,
Cocco
